language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
script: 
    - virtualenv venv
    - source venv/bin/activate
    - cd livestreamer && python setup.py install && cd ..
    - ./test.sh

addons:
  apt:
    packages:
      - ffmpeg
      - rtmpdump
