language: python
sudo: false
python:
  - 3.3
script: 
    - virtualenv venv
    - source venv/bin/activate
    - cd livestreamer && python setup.py -q install && cd ..
    - ./test.sh

addons:
  apt:
    packages:
      - ffmpeg
      - rtmpdump
