language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
script: 
    - cd livestreamer && sudo python setup.py install
    - test.sh

addons:
  apt:
    packages:
      - ffmpeg
      - rtmpdump
